name: network-api-support
version: '0.3.5'
synopsis: Toolkit for building http client libraries over Network.Http.Conduit
description: |-
  Toolkit for building http client libraries over Network.Http.Conduit.

  /Note/: Examples of use can be found in the pin and postmark client libraries.
category: Network APIs
author: Mark Hibberd <mark@hibberd.id.au>
maintainer: Mark Hibberd <mark@hibberd.id.au>
copyright: (c) 2012 Mark Hibberd
license: BSD3
github: markhibberd/network-api-support.git
ghc-options: -Wall
library:
  source-dirs: src
  ghc-options:
  - -fno-warn-orphans
  exposed-modules:
  - Network.Api.Support
  - Network.Api.Support.Core
  - Network.Api.Support.Request
  - Network.Api.Support.Response
  dependencies:
  - base >=3 && <6
  - aeson >=0.5 && <2
  - attoparsec >=0.10 && <0.15
  - bytestring >=0.9.1.5 && <0.12
  - case-insensitive >=0.2 && <1.3
  - http-types >=0.6 && <0.13
  - http-client >=0.2.2.2 && <0.8
  - http-client-tls >=0.2.1.1 && <0.4
  - text >=0.11 && <1.3
  - time ==1.*
  - tls >=1.2.0 && <1.6
tests:
  network-api-support-test:
    main: Main.hs
    source-dirs: test
    ghc-options:
    - -O2
    - -fhpc
    - -fwarn-tabs
    dependencies:
    - base >=3 && <5
    - http-client
    - network-api-support
    - QuickCheck
    - test-framework
    - test-framework-quickcheck2
    - test-framework-hunit
tested-with: ghc ==7.10.3 ghc ==8.0.2
